[build]
publish = "src/"
command = "pnpm run check"

[functions]
directory = "netlify_functions"
node_bundler = "esbuild"

[dev]
framework = "#custom"
command = "browser-sync src -w --port 8080 --no-open"
targetPort = 8080
